# Class 3: Pandas

Pandas is a Python library for handling data associated with variables. The 3 most commonly used data types are integers, real numbers (floats) and objects (strings). Data is handled through DataFrames. These show an Excel-like matrix with one (or more if you want) indexes and named columns.

Unlike classic Python dictionaries, DataFrames allow data manipulation in a much easier way. In addition, through Pandas we can read and save data that comes from classic storage formats such as Excel templates.

Pandas allows you to do everything a person can do in Excel and much more. The big difference is that with Python there is no user interface like in Excel. This is good and bad. The good thing is that it allows you much greater freedom of action, the bad thing is that it is a little less intuitive. In general, for simple things an Excel template can be enough. But if we have to do a more interesting data analysis, it is recommended to use programming tools such as Python's Pandas.

## Loading libraries and data

First we import the Pandas and Numpy libraries (we import the latter in case we have to deal with NaNs).
To save typing so much we abbreviate them as pd and np respectively.

In [1]:
import pandas as pd
import numpy as np

To import data, two things are needed:
- Know the extension of the file that contains the data.
- Know the location (path) of the file.

<h3>Read/Save data formats</h3>

|    Data Format      |        Reed       |            Save    |
| --------------------| :---------------: |--- --------------: |
| csv                 |  `pd.read_csv()`  |   `df.to_csv()`    |
| json                |  `pd.read_json()` |  `df.to_json()`    |
| excel               | `pd.read_excel()` | `df.to_excel()`    |
| hdf                 |  `pd.read_hdf()`  |   `df.to_hdf()`    |
| sql                 |  `pd.read_sql()`  |   `df.to_sql()`    |

There are more formats than these, but these are the most common

The location is usually located in one of two places: the hard drive of our computer or on the Internet. In either case, the process is the same, the location (path) of the file is obtained and passed as a variable in the corresponding pandas module. To simplify the reading of the program, the path is saved as a separate variable.

Next, we will load the shoe data

In [2]:
path = 'shopify.en.csv'
df = pd.read_csv(path)
df

,Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Option2 Name,...,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Variant Barcode,Variant Weight Unit,Image Src,Image Alt Text,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,NaN,True,Size,S/M,NaN,...,manual,18.94,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False
1,18834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
2,18834,NaN,NaN,NaN,NaN,NaN,NaN,Size,L/XL,NaN,...,manual,18.94,0.0,False,False,NaN,NaN,NaN,NaN,NaN
3,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,NaN,True,Size,S/M,NaN,...,manual,16.52,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False
4,18833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4195,1799,NaN,NaN,NaN,NaN,NaN,NaN,Size,L,NaN,...,manual,19.58,0.0,False,False,NaN,NaN,NaN,NaN,NaN
4196,1265,1605-1 Pleated dress with silver cubic zirconi...,Pleated dress with silver cubic zirconia along...,REDIAL,Dresses,NaN,True,Size,S,NaN,...,manual,7.71,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False
4197,1265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
4198,1265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
4199,1265,NaN,NaN,NaN,NaN,NaN,NaN,Size,M,NaN,...,manual,7.71,0.0,False,False,NaN,NaN,NaN,NaN,NaN

## Cleaning the Data

The first thing to do when creating the DataFrame is to clean the data that is not useful so that we can work better.

Sometimes we want to see if what we are doing works or not, but we don't want to visualize the whole DF. For that we have the .head() and .tail() commands.

In [3]:
# .head(x) shows us the first x rows, if not specified it will always be 5
df.head(1)

,Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Option2 Name,...,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Variant Barcode,Variant Weight Unit,Image Src,Image Alt Text,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,NaN,True,Size,S/M,NaN,...,manual,18.94,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False

In [4]:
# .tail(x) shows us the last x rows, if not specified it is always 5
df.tail(2)

,Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Option2 Name,...,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Variant Barcode,Variant Weight Unit,Image Src,Image Alt Text,Gift Card
4198,1265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
4199,1265,NaN,NaN,NaN,NaN,NaN,NaN,Size,M,NaN,...,manual,7.71,0.0,False,False,NaN,NaN,NaN,NaN,NaN

In [6]:
# .info() gives us the type of values that each column has and how many of them are NOT null.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Handle                       4200 non-null   int64
 1   Title                        836 non-null    object
 2   Body (HTML)                  832 non-null    object
 3   Vendor                       836 non-null    object
 4   Type                         818 non-null    object
 5   Tags                         0 non-null      float64
 6   Published                    836 non-null    object
 7   Option1 Name                 2296 non-null   object
 8   Option1 Value                2296 non-null   object
 9   Option2 Name                 0 non-null      float64
 10  Option2 Value                0 non-null      float64
 11  Option3 Name                 0 non-null      float64
 12  Option3 Value                0 non-null      float64
 13  Variant SKU                  2296 non-null   object
 14  Variant Grams                2296 non-null   float64
 15  Variant Inventory Tracker    2296 non-null   object
 16  Variant Inventory Quantity   2296 non-null   float64
 17  Variant Inventory Policy     2296 non-null   object
 18  Variant Fulfillment Service  2296 non-null   object
 19  Variant Price                2296 non-null   float64
 20  Variant Compare at Price     2296 non-null   float64
 21  Variant Requires Shipping    2296 non-null   object
 22  Variant Taxable              2296 non-null   object
 23  Variant Barcode              0 non-null      float64
 24  Variant Weight Unit          0 non-null      float64
 25  Image Src                    2740 non-null   object
 26  Image Alt Text               0 non-null      float64
 27  Gift Card                    836 non-null    object
dtypes: float64(12), int64(1), object(15)
memory usage: 918.9+ KB

We can see that there are at least 8 columns that do not have any useful data. So let's first delete those columns from our DF.

In [5]:
# First we look at the names of the columns so we know how to write them throughout the program.
df.columns

Index(['Handle', 'Title', 'Body (HTML)', 'Vendor', 'Type', 'Tags', 'Published',
       'Option1 Name', 'Option1 Value', 'Option2 Name', 'Option2 Value',
       'Option3 Name ', 'Option3 Value', 'Variant SKU', 'Variant Grams',
       'Variant Inventory Tracker', 'Variant Inventory Quantity',
       'Variant Inventory Policy', 'Variant Fulfillment Service',
       'Variant Price', 'Variant Compare at Price',
       'Variant Requires Shipping', 'Variant Taxable', 'Variant Barcode',
       'Variant Weight Unit', 'Image Src', 'Image Alt Text', 'Gift Card'],
      dtype='object')

In [6]:
#We remove the columns that are not useful:
df.drop(['Tags', 'Option2 Name', 'Option2 Value','Option3 Name ','Option3 Value', 'Variant Barcode','Variant Weight Unit',
        'Image Alt Text'], axis=1)
df.head()

,Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Option2 Name,...,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Variant Barcode,Variant Weight Unit,Image Src,Image Alt Text,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,NaN,True,Size,S/M,NaN,...,manual,18.94,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False
1,18834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN
2,18834,NaN,NaN,NaN,NaN,NaN,NaN,Size,L/XL,NaN,...,manual,18.94,0.0,False,False,NaN,NaN,NaN,NaN,NaN
3,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,NaN,True,Size,S/M,NaN,...,manual,16.52,0.0,False,False,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,False
4,18833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN,NaN

This deleted the columns temporarily. When we call DF again, the columns are still there.
To delete permanently, we have to specify it!!! To do this, change the parameter "inplace" to true (it is false by default)

In [7]:
df.drop(['Tags', 'Option2 Name', 'Option2 Value','Option3 Name ','Option3 Value', 'Variant Barcode','Variant Weight Unit',
        'Image Alt Text'], axis=1, inplace = True)
df.head()

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,True,Size,S/M,72035-1,0.0,shopify,5.0,deny,manual,18.94,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
1,18834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN
2,18834,NaN,NaN,NaN,NaN,NaN,Size,L/XL,72035-1,0.0,shopify,2.0,deny,manual,18.94,0.0,False,False,NaN,NaN
3,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,True,Size,S/M,72034-1,0.0,shopify,5.0,deny,manual,16.52,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
4,18833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://yournewstyle.pl/files/clothes/preview/...,NaN

We have deleted the columns that are not useful. But there are still many NaNs. Let's continue cleaning up the DataFrame.

Another great tool in Pandas is the .describe() module

In [8]:
# .describe() gives us a quick analysis for all columns that have numeric values (int or float)
df.describe()

,Handle,Variant Grams,Variant Inventory Quantity,Variant Price,Variant Compare at Price
count,4200.000000,2296.0,2296.000000,2296.000000,2296.0
mean,17420.672381,0.0,2.033972,19.650405,0.0
std,2991.817304,0.0,3.154783,10.460283,0.0
min,1265.000000,0.0,0.000000,3.720000,0.0
25%,17775.000000,0.0,0.000000,10.790000,0.0
50%,18080.000000,0.0,1.000000,17.610000,0.0
75%,18452.250000,0.0,3.000000,26.430000,0.0
max,18834.000000,0.0,45.000000,50.440000,0.0

The describe module skips all NaN values
- Count does not return the number of rows that have values within the DF
- mean returns the average of that column
- std returns the standard deviation
- min returns the minimum value of the column
- 25% returns the value equivalent to 25% (whether it exists or not)
- 50% returns the value equivalent to 50% (whether it exists or not)
- 75% returns the value equivalent to 75% (whether it exists or not)
- max returns the maximum value of the column

In [9]:
# .describe() also allows viewing information about columns with objects if specified.
df.describe(include='all')

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
count,4200.000000,836,832,836,818,836,2296,2296,2296,2296.0,2296,2296.000000,2296,2296,2296.000000,2296.0,2296,2296,2740,836
unique,NaN,836,788,34,27,1,1,35,836,NaN,1,NaN,1,1,NaN,NaN,1,1,2740,1
top,NaN,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,t-shirt,EVA&LOLA,Dresses,True,Size,S,16001-2,NaN,shopify,NaN,deny,manual,NaN,NaN,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
freq,NaN,1,20,193,370,836,2296,527,8,NaN,2296,NaN,2296,2296,NaN,NaN,2296,2296,1,836
mean,17420.672381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.033972,NaN,NaN,19.650405,0.0,NaN,NaN,NaN,NaN
std,2991.817304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.154783,NaN,NaN,10.460283,0.0,NaN,NaN,NaN,NaN
min,1265.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,NaN,NaN,3.720000,0.0,NaN,NaN,NaN,NaN
25%,17775.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,NaN,NaN,10.790000,0.0,NaN,NaN,NaN,NaN
50%,18080.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.000000,NaN,NaN,17.610000,0.0,NaN,NaN,NaN,NaN
75%,18452.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.000000,NaN,NaN,26.430000,0.0,NaN,NaN,NaN,NaN
max,18834.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,45.000000,NaN,NaN,50.440000,0.0,NaN,NaN,NaN,NaN

In the case of columns with objects, we have

- unique tells us how many unique values there are in the column
- top tells us the most repeated value in the column
- freq gives us the frequency with which the top value in the column is repeated

Columns with numeric values will present NaN for unique, top and freq. While columns with objects will present NaN for all other values

We can specify to only see the objects using .describe(include='object')

In [10]:
df.describe(include='object')

,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Inventory Tracker,Variant Inventory Policy,Variant Fulfillment Service,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
count,836,832,836,818,836,2296,2296,2296,2296,2296,2296,2296,2296,2740,836
unique,836,788,34,27,1,1,35,836,1,1,1,1,1,2740,1
top,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,t-shirt,EVA&LOLA,Dresses,True,Size,S,16001-2,shopify,deny,manual,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
freq,1,20,193,370,836,2296,527,8,2296,2296,2296,2296,2296,1,836

Now we need to start making decisions about what to keep and what to remove. To do this we can run a simple code that lets us know how many values are null. First we create an extra DataFrame to see the NaNs

In [11]:
missing_data = df.isnull()
missing_data.head()

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True
2,False,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True

This gives us a DF that has only Booleans. True, if it is a NaN, False if it is a usable value.

In [12]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

Handle
False    4200
Name: Handle, dtype: int64

Title
True     3364
False     836
Name: Title, dtype: int64

Body (HTML)
True     3368
False     832
Name: Body (HTML), dtype: int64

Vendor
True     3364
False     836
Name: Vendor, dtype: int64

Type
True     3382
False     818
Name: Type, dtype: int64

Published
True     3364
False     836
Name: Published, dtype: int64

Option1 Name
False    2296
True     1904
Name: Option1 Name, dtype: int64

Option1 Value
False    2296
True     1904
Name: Option1 Value, dtype: int64

Variant SKU
False    2296
True     1904
Name: Variant SKU, dtype: int64

Variant Grams
False    2296
True     1904
Name: Variant Grams, dtype: int64

Variant Inventory Tracker
False    2296
True     1904
Name: Variant Inventory Tracker, dtype: int64

Variant Inventory Quantity
False    2296
True     1904
Name: Variant Inventory Quantity, dtype: int64

Variant Inventory Policy
False    2296
True     1904
Name: Variant Inventory Policy, dtype: int64

Variant Fulfillment Service
False    2296
True     1904
Name: Variant Fulfillment Service, dtype: int64

Variant Price
False    2296
True     1904
Name: Variant Price, dtype: int64

Variant Compare at Price
False    2296
True     1904
Name: Variant Compare at Price, dtype: int64

Variant Requires Shipping
False    2296
True     1904
Name: Variant Requires Shipping, dtype: int64

Variant Taxable
False    2296
True     1904
Name: Variant Taxable, dtype: int64

Image Src
False    2740
True     1460
Name: Image Src, dtype: int64

Gift Card
True     3364
False     836
Name: Gift Card, dtype: int64

From here we can make certain decisions. We can replace data with our estimates or we can simply delete the corresponding columns or rows.

To replace we can use
- Frequency
- Average
- Something else that makes sense

In this case we are going to keep all the elements that were actually published and delete everything that was not published. Then we will see how our data is.

In [13]:
# Remove all NaNs from the Published column
df.dropna(subset=["Published"], axis=0, inplace=True)

df.head()

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,True,Size,S/M,72035-1,0.0,shopify,5.0,deny,manual,18.94,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
3,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,True,Size,S/M,72034-1,0.0,shopify,5.0,deny,manual,16.52,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
6,18832,OBSESSIVE 838-BAB-3 BABYDOLL & THONG RED 72033-2,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Nightdress,True,Size,S/M,72033-2,0.0,shopify,3.0,deny,manual,19.60,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
10,18831,OBSESSIVE 838-BAB-1 BABYDOLL & THONG BLACK 72...,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Night dresses,True,Size,S/M,72033-1,0.0,shopify,5.0,deny,manual,19.60,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
14,18830,OBSESSIVE 830-TED-1 TEDDY 72032-1,Check more details:\r\n- alluring teddy with o...,OBSESSIVE,Bodystocking,True,Size,S/M,72032-1,0.0,shopify,5.0,deny,manual,14.54,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

We can see that the index has not been altered. This is easily fixable.

In [14]:
# Reset the index
df.reset_index(drop=True, inplace=True)

In [15]:
df.head()

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,True,Size,S/M,72035-1,0.0,shopify,5.0,deny,manual,18.94,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
1,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,True,Size,S/M,72034-1,0.0,shopify,5.0,deny,manual,16.52,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
2,18832,OBSESSIVE 838-BAB-3 BABYDOLL & THONG RED 72033-2,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Nightdress,True,Size,S/M,72033-2,0.0,shopify,3.0,deny,manual,19.60,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
3,18831,OBSESSIVE 838-BAB-1 BABYDOLL & THONG BLACK 72...,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Night dresses,True,Size,S/M,72033-1,0.0,shopify,5.0,deny,manual,19.60,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
4,18830,OBSESSIVE 830-TED-1 TEDDY 72032-1,Check more details:\r\n- alluring teddy with o...,OBSESSIVE,Bodystocking,True,Size,S/M,72032-1,0.0,shopify,5.0,deny,manual,14.54,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

We look again at the data we have.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 836 entries, 0 to 835
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Handle                       836 non-null    int64
 1   Title                        836 non-null    object
 2   Body (HTML)                  832 non-null    object
 3   Vendor                       836 non-null    object
 4   Type                         818 non-null    object
 5   Published                    836 non-null    object
 6   Option1 Name                 836 non-null    object
 7   Option1 Value                836 non-null    object
 8   Variant SKU                  836 non-null    object
 9   Variant Grams                836 non-null    float64
 10  Variant Inventory Tracker    836 non-null    object
 11  Variant Inventory Quantity   836 non-null    float64
 12  Variant Inventory Policy     836 non-null    object
 13  Variant Fulfillment Service  836 non-null    object
 14  Variant Price                836 non-null    float64
 15  Variant Compare at Price     836 non-null    float64
 16  Variant Requires Shipping    836 non-null    object
 17  Variant Taxable              836 non-null    object
 18  Image Src                    836 non-null    object
 19  Gift Card                    836 non-null    object
dtypes: float64(4), int64(1), object(15)
memory usage: 130.8+ KB

We notice that there are some rows that still have null values. In particular in the columns Type and Body

In [17]:
df.loc[:,['Body (HTML)']]

                                           Body (HTML)
0    Discover all details:\r\n- black corset in a r...
1    More details? Here you are:\r\n- hot corset ma...
2    Check these details:\r\n- tempting babydoll in...
3    Check these details:\r\n- tempting babydoll in...
4    Check more details:\r\n- alluring teddy with o...
..                                                 ...
831  The elegant trousers, at the top of the corrug...
832  Leggings perfectly matched to the body. Made o...
833  High heels and platform. Includes bow in the f...
834  Long dress, worn on the breast, made of tiulow...
835  Pleated dress with silver cubic zirconia along...

[836 rows x 1 columns]

From here we notice that the Body (HTML) Column simply displays the text that is written associated with the post. That means that 4 posts have no text written and simply display a NaN. We can do two things:

1) Delete those rows
2) Change the NaNs to a text like "Post without text"

Which decision is made will depend on what we are looking to obtain from the data. In general it is always better to keep the data as long as possible, so we will take the second option.

In [18]:
#We replace NaN in Body (HTML) with a text of our choice
texto = 'Post without text.'
df["Body (HTML)"].replace(np.nan, texto, inplace=True)

In the case of the Type column, we need to redo the analysis. Type describes the type of item being sold (dresses, pants, etc.). We also know that there are 18 NaN values that we need to deal with.

First, let's see which are the most repeated items in the column.

In [19]:
df['Type'].value_counts()

Dresses             370
Bodystocking         60
Set                  46
Pantyhose            40
Blouse               36
Accessoiries         33
Costumes             27
Night dresses        25
Sweaters             23
T-shirt              21
SWEAT SUIT           20
Pants, Shorts        18
Panties              15
Jacket and Coat      12
Bra                  11
Long sleeve           9
Babydoll              9
Wigs                  7
Two-piece             7
Jackets               6
Trousers, shorts      6
Skirts                5
Nightdress            5
Shoes                 3
Shirt                 2
Sweater               1
Tops                  1
Name: Type, dtype: int64

Clearly dresses are the best sellers, so it might be a good idea to replace each of those entries with dresses. To confirm this, let's look at the descriptions of the Body column (HTML) associated with those entries.

In order to see such specific information, we can use .isna(), for example with
<pre>df[df.isna().any(axis=1)]</pre>
we could get a sample of all the rows that contain a NaN, regardless of the column. But we already know that we are only interested in the Type column, so we can reduce the code to what is necessary.

In [20]:
#From our data frame, we want to see all the rows with NaN in the Type column
df[df['Type'].isna()]

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
38,18796,MENS UNDERWEAR THONG MICROFIBER - ENVY 71015-2,"Microfiber thong white.<br /><table style=""bor...",Envy,NaN,True,Size,S/M,71015-2,0.0,shopify,10.0,deny,manual,6.56,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
39,18795,MENS UNDERWEAR THONG MICROFIBER - ENVY 71015-1,"Microfiber string black.<br /><table style=""bo...",Envy,NaN,True,Size,S/M,71015-1,0.0,shopify,9.0,deny,manual,6.56,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
40,18794,MENS UNDERWEAR G-STRING MESH - ENVY 71014-1,"Mesh g-string black.<br /><table style=""border...",Envy,NaN,True,Size,S/M,71014-1,0.0,shopify,10.0,deny,manual,5.95,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
41,18793,MENS UNDERWEAR LOW-RISE JOCK WHITE - ENVY 710...,Logo elastic lowrise mesh jock white.<br /><ta...,Envy,NaN,True,Size,S/M,71013-1,0.0,shopify,10.0,deny,manual,8.15,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
42,18792,MENS UNDERWEAR LOGO ELASTIC LOWRISE MESH JOCK ...,Logo elastic lowrise mesh jock white.<br /><ta...,Envy,NaN,True,Size,S/M,71012-1,0.0,shopify,10.0,deny,manual,7.71,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
43,18791,MENS UNDERWEAR LOW RISE THONG RED - ENVY 71011-2,"Low-rise thong red.<br /><table style=""border-...",Envy,NaN,True,Size,S/M,71011-2,0.0,shopify,10.0,deny,manual,6.39,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
44,18790,MENS UNDERWEAR LOW RISE THONG BLACK - ENVY 710...,"Low-rise thong black.<br /><table style=""borde...",Envy,NaN,True,Size,S/M,71011-1,0.0,shopify,9.0,deny,manual,6.39,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
45,18789,MENS UNDERWEAR SET 2 parts - ENVY 71010-1,He's ready to handcuff you and read you your r...,Envy,NaN,True,Size,M/L,71010-1,0.0,shopify,10.0,deny,manual,10.35,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
46,18788,MENS UNDERWEAR SAILOR SALUTE 2 parts - ENVY 71...,Everyone loves a man in uniform! Salute the ma...,Envy,NaN,True,Size,M/L,71009-1,0.0,shopify,10.0,deny,manual,10.79,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
47,18787,MENS UNDERWEAR DOCTOR LOVE 2 parts - ENVY 71008-1,Doctor Love is here to tend to all your needs!...,Envy,NaN,True,Size,M/L,71008-1,0.0,shopify,10.0,deny,manual,11.89,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
48,18786,MENS UNDERWEAR GIDDY UP COWBOY 2 parts - ENVY ...,"Giddy up, Cowboy! This sexy and revealing Cowb...",Envy,NaN,True,Size,M/L,71007-1,0.0,shopify,10.0,deny,manual,10.79,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
49,18785,MENS UNDERWEAR TUXEDO WITH CUFFS/COLLAR 3 part...,"All decked out and nowhere to go, which might ...",Envy,NaN,True,Size,M/L,71006-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
50,18784,MENS UNDERWEAR COP BLUE BOTTOM WITH BADGE/HAT ...,Put your hands behind your back and spread 'em...,Envy,NaN,True,Size,M/L,71005-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
51,18783,MENS UNDERWEAR BIKER BIKINI BOTTOM/CUFF/HAT 3 ...,Stare death in the face and get your gears goi...,Envy,NaN,True,Size,M/L,71004-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
52,18782,MENS UNDERWEAR SWAT 2 parts - ENVY 71003-1,"Don't fear, the S.W.A.T. team is here! Roll up...",Envy,NaN,True,Size,M/L,71003-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
53,18781,MENS UNDERWEAR FIREMAN 2 parts - ENVY 71002-1,"Where there's smoke, there's fire, and this se...",Envy,NaN,True,Size,M/L,71002-1,0.0,shopify,10.0,deny,manual,12.33,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
54,18780,MENS UNDERWEAR SAILOR 3 parts - ENVY 71001-1,All hands on deck! The white trunks are playfu...,Envy,NaN,True,Size,M/L,71001-1,0.0,shopify,10.0,deny,manual,18.72,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
384,18226,BACI BODYSTOCKING BLACK PATTERNED 50008-32,Sexy bodystocking perfectly tailored to the bo...,BACI,NaN,True,Size,XL/XXL,50008-32,0.0,shopify,5.0,deny,manual,9.90,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

Here we can clearly see that the NaNs are associated with multiple items. We can use the Title or Body information to modify each entry, we can put in generic text like we did in Body (HTML), or we can delete those 18 rows.

In this case we will try to change the entries specifically based on the Title info and the other Type categories where appropriate. It is clear to see that all but the last row are for men's underwear, so we will use that category.

In [21]:
#We will change the NaNs in rows 38 to 54 to 'Men's Underwear'
# .loc[] allows us to locate specific locations within the DF. ex: df.loc[Row N, 'Column Name']
texto2 = 'Men´s Underwear'
df.loc[38:54,'Type'].replace(np.nan, texto2, inplace=True)

In [23]:
#Lets see the rows 38 to 54
df.loc[38:54,]

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
38,18796,MENS UNDERWEAR THONG MICROFIBER - ENVY 71015-2,"Microfiber thong white.<br /><table style=""bor...",Envy,Men´s Underwear,True,Size,S/M,71015-2,0.0,shopify,10.0,deny,manual,6.56,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
39,18795,MENS UNDERWEAR THONG MICROFIBER - ENVY 71015-1,"Microfiber string black.<br /><table style=""bo...",Envy,Men´s Underwear,True,Size,S/M,71015-1,0.0,shopify,9.0,deny,manual,6.56,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
40,18794,MENS UNDERWEAR G-STRING MESH - ENVY 71014-1,"Mesh g-string black.<br /><table style=""border...",Envy,Men´s Underwear,True,Size,S/M,71014-1,0.0,shopify,10.0,deny,manual,5.95,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
41,18793,MENS UNDERWEAR LOW-RISE JOCK WHITE - ENVY 710...,Logo elastic lowrise mesh jock white.<br /><ta...,Envy,Men´s Underwear,True,Size,S/M,71013-1,0.0,shopify,10.0,deny,manual,8.15,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
42,18792,MENS UNDERWEAR LOGO ELASTIC LOWRISE MESH JOCK ...,Logo elastic lowrise mesh jock white.<br /><ta...,Envy,Men´s Underwear,True,Size,S/M,71012-1,0.0,shopify,10.0,deny,manual,7.71,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
43,18791,MENS UNDERWEAR LOW RISE THONG RED - ENVY 71011-2,"Low-rise thong red.<br /><table style=""border-...",Envy,Men´s Underwear,True,Size,S/M,71011-2,0.0,shopify,10.0,deny,manual,6.39,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
44,18790,MENS UNDERWEAR LOW RISE THONG BLACK - ENVY 710...,"Low-rise thong black.<br /><table style=""borde...",Envy,Men´s Underwear,True,Size,S/M,71011-1,0.0,shopify,9.0,deny,manual,6.39,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
45,18789,MENS UNDERWEAR SET 2 parts - ENVY 71010-1,He's ready to handcuff you and read you your r...,Envy,Men´s Underwear,True,Size,M/L,71010-1,0.0,shopify,10.0,deny,manual,10.35,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
46,18788,MENS UNDERWEAR SAILOR SALUTE 2 parts - ENVY 71...,Everyone loves a man in uniform! Salute the ma...,Envy,Men´s Underwear,True,Size,M/L,71009-1,0.0,shopify,10.0,deny,manual,10.79,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
47,18787,MENS UNDERWEAR DOCTOR LOVE 2 parts - ENVY 71008-1,Doctor Love is here to tend to all your needs!...,Envy,Men´s Underwear,True,Size,M/L,71008-1,0.0,shopify,10.0,deny,manual,11.89,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
48,18786,MENS UNDERWEAR GIDDY UP COWBOY 2 parts - ENVY ...,"Giddy up, Cowboy! This sexy and revealing Cowb...",Envy,Men´s Underwear,True,Size,M/L,71007-1,0.0,shopify,10.0,deny,manual,10.79,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
49,18785,MENS UNDERWEAR TUXEDO WITH CUFFS/COLLAR 3 part...,"All decked out and nowhere to go, which might ...",Envy,Men´s Underwear,True,Size,M/L,71006-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
50,18784,MENS UNDERWEAR COP BLUE BOTTOM WITH BADGE/HAT ...,Put your hands behind your back and spread 'em...,Envy,Men´s Underwear,True,Size,M/L,71005-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
51,18783,MENS UNDERWEAR BIKER BIKINI BOTTOM/CUFF/HAT 3 ...,Stare death in the face and get your gears goi...,Envy,Men´s Underwear,True,Size,M/L,71004-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
52,18782,MENS UNDERWEAR SWAT 2 parts - ENVY 71003-1,"Don't fear, the S.W.A.T. team is here! Roll up...",Envy,Men´s Underwear,True,Size,M/L,71003-1,0.0,shopify,10.0,deny,manual,17.40,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
53,18781,MENS UNDERWEAR FIREMAN 2 parts - ENVY 71002-1,"Where there's smoke, there's fire, and this se...",Envy,Men´s Underwear,True,Size,M/L,71002-1,0.0,shopify,10.0,deny,manual,12.33,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
54,18780,MENS UNDERWEAR SAILOR 3 parts - ENVY 71001-1,All hands on deck! The white trunks are playfu...,Envy,Men´s Underwear,True,Size,M/L,71001-1,0.0,shopify,10.0,deny,manual,18.72,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

Now we just need to modify row 384, but we also confirm that it is only one with .info()

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 836 entries, 0 to 835
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Handle                       836 non-null    int64
 1   Title                        836 non-null    object
 2   Body (HTML)                  836 non-null    object
 3   Vendor                       836 non-null    object
 4   Type                         835 non-null    object
 5   Published                    836 non-null    object
 6   Option1 Name                 836 non-null    object
 7   Option1 Value                836 non-null    object
 8   Variant SKU                  836 non-null    object
 9   Variant Grams                836 non-null    float64
 10  Variant Inventory Tracker    836 non-null    object
 11  Variant Inventory Quantity   836 non-null    float64
 12  Variant Inventory Policy     836 non-null    object
 13  Variant Fulfillment Service  836 non-null    object
 14  Variant Price                836 non-null    float64
 15  Variant Compare at Price     836 non-null    float64
 16  Variant Requires Shipping    836 non-null    object
 17  Variant Taxable              836 non-null    object
 18  Image Src                    836 non-null    object
 19  Gift Card                    836 non-null    object
dtypes: float64(4), int64(1), object(15)
memory usage: 130.8+ KB

In [25]:
#we show 3 rows to have a little context.
df.loc[383:385,]

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Grams,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Compare at Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
383,18227,BACI BODYSTOCKING BLACK PATTERNED 50008-33,Sexy bodystocking perfectly tailored to the bo...,BACI,Bodystocking,True,Size,XL/XXL,50008-33,0.0,shopify,7.0,deny,manual,11.66,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
384,18226,BACI BODYSTOCKING BLACK PATTERNED 50008-32,Sexy bodystocking perfectly tailored to the bo...,BACI,NaN,True,Size,XL/XXL,50008-32,0.0,shopify,5.0,deny,manual,9.90,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
385,18225,BACI BODYSTOCKING BLACK PATTERNED 50008-31,Sexy bodystocking perfectly tailored to the bo...,BACI,Bodystocking,True,Size,XL/XXL,50008-31,0.0,shopify,6.0,deny,manual,12.76,0.0,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

From here we clearly notice that there was a data entry error, as the NaN element should be Bodystocking. So we replace this value with the correct one.

To get the exact name we use the command .iloc[][]

In [26]:
# .iloc[][] allows you to access a specific cell using its numeric value

print(df.iloc[384][4]) #We see that this is the NaN
print(df.iloc[385][4]) #We see that this is the value we are looking for

texto3 = df.iloc[385][4]
df['Type'].replace(np.nan, texto3, inplace=True) #We change all the NaNs (the only one left in this case).

print(df.iloc[384][4]) #Check that the value has changed

nan
Bodystocking
Bodystocking

Finally we remove the two columns that have no useful information: Variant Grams and Variant Compare at Price.

We know that they have no useful information because all their values are zero, we can see this with .describe()

In [28]:
df.describe()

,Handle,Variant Grams,Variant Inventory Quantity,Variant Price,Variant Compare at Price
count,836.000000,836.0,836.000000,836.000000,836.0
mean,17599.351675,0.0,2.966507,18.444426,0.0
std,2702.932173,0.0,4.272046,10.158829,0.0
min,1265.000000,0.0,0.000000,3.720000,0.0
25%,17858.750000,0.0,0.000000,10.560000,0.0
50%,18192.500000,0.0,2.000000,15.400000,0.0
75%,18458.750000,0.0,5.000000,26.045000,0.0
max,18834.000000,0.0,45.000000,50.440000,0.0

In [29]:
df.drop(['Variant Grams', 'Variant Compare at Price'], axis=1,inplace = True)

## Saving the DF

Very important, now that we have a sorted DataFrame, it is best to save this data in a new file. This way we do not have to clean it every time we want to work with it.

In [30]:
path='Clean_Data.csv'
df.to_csv(path)

## Finally, lets work with the data!

Now that we have a tidy data set, we can start asking questions and try to answer them using the data.

First let's see what kind of data we have and what questions we can ask them.

In [31]:
df.head()

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
0,18834,OBSESSIVE 838-COR-1 CORSET & THONG BLACK 72035-1,Discover all details:\r\n- black corset in a r...,OBSESSIVE,Set,True,Size,S/M,72035-1,shopify,5.0,deny,manual,18.94,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
1,18833,[koOBSESSIVE 838-COR-3 CORSET & THONG RED 720...,More details? Here you are:\r\n- hot corset ma...,OBSESSIVE,Set,True,Size,S/M,72034-1,shopify,5.0,deny,manual,16.52,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
2,18832,OBSESSIVE 838-BAB-3 BABYDOLL & THONG RED 72033-2,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Nightdress,True,Size,S/M,72033-2,shopify,3.0,deny,manual,19.60,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
3,18831,OBSESSIVE 838-BAB-1 BABYDOLL & THONG BLACK 72...,Check these details:\r\n- tempting babydoll in...,OBSESSIVE,Night dresses,True,Size,S/M,72033-1,shopify,5.0,deny,manual,19.60,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
4,18830,OBSESSIVE 830-TED-1 TEDDY 72032-1,Check more details:\r\n- alluring teddy with o...,OBSESSIVE,Bodystocking,True,Size,S/M,72032-1,shopify,5.0,deny,manual,14.54,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

### Which brand has the most inventory?

For this we will use .groupby()

This tool allows us to choose specific columns to which to apply a condition and thus be able to compare them

In [32]:
#We add up all the values in each column with numbers and group them by the different entries in the Vendor column
df.groupby('Vendor').sum()

                  Handle  Variant Inventory Quantity  Variant Price
Vendor
119 FASHION        74103                         6.0          98.67
7Heaven           747844                       184.0         757.47
ATTRAIT            71523                         2.0         116.51
AYANAPA            15250                         0.0           7.91
AZAKA             378951                        56.0         203.82
BACI             1823705                       447.0        1094.20
BYE-BRA           643871                       532.0         308.08
CANDY BRUSH        15292                         0.0           7.71
CIMINY            448846                        49.0         321.38
CRSM              605597                        27.0         366.18
D.N.D. RAW          2424                         0.0           4.19
DISPLAY             2542                         0.0           9.91
DIVA LONDON        15254                         0.0          10.57
DROLE DE COPINE    24224                         4.0          32.36
EMAMODA           872577                        41.0         642.98
EVA&LOLA         3501965                       200.0        5755.95
Envy              319396                       168.0         192.18
FIONELLA            3733                         0.0          30.37
FREESIA           161306                         7.0         152.20
G-LADIES            2658                         1.0           7.71
GOLDEN DAYS         5943                         5.0          19.82
Kelyna             17916                         0.0          10.79
Lily McBee         35839                         6.0          57.05
NIKKA              76305                         6.0          42.95
OBSESSIVE        1757582                       474.0        1455.56
P.L               165771                       120.0         192.25
PINK BOOM         255996                        12.0         403.76
REDIAL             39272                         3.0          43.56
REDOX             436649                        12.0         438.81
SHAKO               1931                         0.0          11.89
SINLY SHOES         1855                         0.0           5.51
SOKY&SOKA        1292342                        46.0        1949.09
SUNRISE C           2197                         0.0           5.51
YNS               892399                        72.0         662.64

In [33]:
# But we can be more specific and ask it to order them.
df.groupby('Vendor').sum().sort_values('Variant Inventory Quantity' , ascending=False)

                  Handle  Variant Inventory Quantity  Variant Price
Vendor
BYE-BRA           643871                       532.0         308.08
OBSESSIVE        1757582                       474.0        1455.56
BACI             1823705                       447.0        1094.20
EVA&LOLA         3501965                       200.0        5755.95
7Heaven           747844                       184.0         757.47
Envy              319396                       168.0         192.18
P.L               165771                       120.0         192.25
YNS               892399                        72.0         662.64
AZAKA             378951                        56.0         203.82
CIMINY            448846                        49.0         321.38
SOKY&SOKA        1292342                        46.0        1949.09
EMAMODA           872577                        41.0         642.98
CRSM              605597                        27.0         366.18
PINK BOOM         255996                        12.0         403.76
REDOX             436649                        12.0         438.81
FREESIA           161306                         7.0         152.20
NIKKA              76305                         6.0          42.95
Lily McBee         35839                         6.0          57.05
119 FASHION        74103                         6.0          98.67
GOLDEN DAYS         5943                         5.0          19.82
DROLE DE COPINE    24224                         4.0          32.36
REDIAL             39272                         3.0          43.56
ATTRAIT            71523                         2.0         116.51
G-LADIES            2658                         1.0           7.71
Kelyna             17916                         0.0          10.79
DIVA LONDON        15254                         0.0          10.57
DISPLAY             2542                         0.0           9.91
D.N.D. RAW          2424                         0.0           4.19
CANDY BRUSH        15292                         0.0           7.71
AYANAPA            15250                         0.0           7.91
SHAKO               1931                         0.0          11.89
SINLY SHOES         1855                         0.0           5.51
SUNRISE C           2197                         0.0           5.51
FIONELLA            3733                         0.0          30.37

In [34]:
# We can be even more specific and ask it to only show us the column we want.
df.groupby('Vendor').sum().sort_values('Variant Inventory Quantity' , ascending=False)['Variant Inventory Quantity']

Vendor
BYE-BRA            532.0
OBSESSIVE          474.0
BACI               447.0
EVA&LOLA           200.0
7Heaven            184.0
Envy               168.0
P.L                120.0
YNS                 72.0
AZAKA               56.0
CIMINY              49.0
SOKY&SOKA           46.0
EMAMODA             41.0
CRSM                27.0
PINK BOOM           12.0
REDOX               12.0
FREESIA              7.0
NIKKA                6.0
Lily McBee           6.0
119 FASHION          6.0
GOLDEN DAYS          5.0
DROLE DE COPINE      4.0
REDIAL               3.0
ATTRAIT              2.0
G-LADIES             1.0
Kelyna               0.0
DIVA LONDON          0.0
DISPLAY              0.0
D.N.D. RAW           0.0
CANDY BRUSH          0.0
AYANAPA              0.0
SHAKO                0.0
SINLY SHOES          0.0
SUNRISE C            0.0
FIONELLA             0.0
Name: Variant Inventory Quantity, dtype: float64

### What are all the Envy brand products that are also dresses?

In [35]:
df.loc[(df['Vendor']== 'Envy') & (df['Type']=='Dresses')]

Empty DataFrame
Columns: [Handle, Title, Body (HTML), Vendor, Type, Published, Option1 Name, Option1 Value, Variant SKU, Variant Inventory Tracker, Variant Inventory Quantity, Variant Inventory Policy, Variant Fulfillment Service, Variant Price, Variant Requires Shipping, Variant Taxable, Image Src, Gift Card]
Index: []

We quickly see that Envy did not publish any dresses. How about EVA&LOLA?

In [36]:
df.loc[(df['Vendor']== 'EVA&LOLA') & (df['Type']=='Dresses')]

,Handle,Title,Body (HTML),Vendor,Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
95,18675,SENAT SIREN DRESS BLACK 68008-3,"Fitted dress with sequins, mermaid cut.<br /><...",EVA&LOLA,Dresses,True,Size,S,68008-3,shopify,1.0,deny,manual,40.09,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
96,18674,SENAT SIREN DRESS RED 68008-2,"Fitted dress with sequins, mermaid cut.<br /><...",EVA&LOLA,Dresses,True,Size,S,68008-2,shopify,0.0,deny,manual,40.09,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
97,18672,SENAT BOLERO DRESS CHERRY 68007-3,One shoulder long satin dress + bolero.<br /><...,EVA&LOLA,Dresses,True,Size,S,68007-3,shopify,1.0,deny,manual,27.31,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
98,18671,SENAT BOLERO DRESS PINK 68007-2,One shoulder long satin dress + bolero.<br /><...,EVA&LOLA,Dresses,True,Size,S,68007-2,shopify,0.0,deny,manual,27.31,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
99,18670,SENAT BOLERO DRESS NAVY BLUE 68007-1,One shoulder long satin dress + bolero.<br /><...,EVA&LOLA,Dresses,True,Size,S,68007-1,shopify,0.0,deny,manual,27.31,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,16236,EVA & LOLA DRESS - FUCHSIA 7816-3,"strapless neckline, neckline very fashionably ...",EVA&LOLA,Dresses,True,Size,S,7816-3,shopify,0.0,deny,manual,36.51,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
782,16114,EVA & LOLA DRESS -RED 7910-2,"scoop neckline, neckline very fashionably deco...",EVA&LOLA,Dresses,True,Size,S,7910-2,shopify,1.0,deny,manual,18.07,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
783,16113,EVA & LOLA DRESS -BLUE 8020-3,"square neckline, lace neckline, slit neckline,...",EVA&LOLA,Dresses,True,Size,S,8020-3,shopify,0.0,deny,manual,19.09,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
793,15963,EVA & LOLA DRESS 7815-3,"scoop neckline, sweetheart neckline, lace neck...",EVA&LOLA,Dresses,True,Size,S,7815-3,shopify,1.0,deny,manual,27.35,False,False,https://yournewstyle.pl/files/clothes/preview/...,False
821,2552,3701-2 Elegant dress with usztywnianymi bowls ...,Matching women's dress is made from high quali...,EVA&LOLA,Dresses,True,Size,S,3701-2,shopify,0.0,deny,manual,20.70,False,False,https://yournewstyle.pl/files/clothes/preview/...,False

We see that there are many, is it all of them?

In [37]:
df.loc[(df['Vendor']== 'EVA&LOLA') & (df['Type']!='Dresses')]

Empty DataFrame
Columns: [Handle, Title, Body (HTML), Vendor, Type, Published, Option1 Name, Option1 Value, Variant SKU, Variant Inventory Tracker, Variant Inventory Quantity, Variant Inventory Policy, Variant Fulfillment Service, Variant Price, Variant Requires Shipping, Variant Taxable, Image Src, Gift Card]
Index: []

Yes, its all of them

### Which brands sell dresses?

First we have to see all the types of dresses that there are

In [38]:
df['Type'].value_counts()

Dresses             370
Bodystocking         61
Set                  46
Pantyhose            40
Blouse               36
Accessoiries         33
Costumes             27
Night dresses        25
Sweaters             23
T-shirt              21
SWEAT SUIT           20
Pants, Shorts        18
Men´s Underwear      17
Panties              15
Jacket and Coat      12
Bra                  11
Long sleeve           9
Babydoll              9
Two-piece             7
Wigs                  7
Jackets               6
Trousers, shorts      6
Skirts                5
Nightdress            5
Shoes                 3
Shirt                 2
Sweater               1
Tops                  1
Name: Type, dtype: int64

We notice that there are 3: Dresses, Nightdress and Night dresses. Each category is written differently, but we can see that they all have the letters "ress" and that no other category has them. This is what we will use to group them together.

In [40]:
#We save the data in a new dataframe to be able to continue analyzing it in greater depth
df_dresses = df.loc[df['Type'].str.contains('ress')]

In [41]:
#To see how many dresses each brand sells
df_dresses['Vendor'].value_counts()

EVA&LOLA           193
SOKY&SOKA           71
EMAMODA             47
YNS                 20
PINK BOOM           20
OBSESSIVE           14
7Heaven             14
119 FASHION          4
DROLE DE COPINE      3
CIMINY               3
FIONELLA             2
Lily McBee           2
BACI                 2
AYANAPA              1
CANDY BRUSH          1
AZAKA                1
G-LADIES             1
REDIAL               1
Name: Vendor, dtype: int64

### How many items does each brand sell?

In [42]:
#Again with groupby we can count by column
df.groupby('Vendor').count()

,Handle,Title,Body (HTML),Type,Published,Option1 Name,Option1 Value,Variant SKU,Variant Inventory Tracker,Variant Inventory Quantity,Variant Inventory Policy,Variant Fulfillment Service,Variant Price,Variant Requires Shipping,Variant Taxable,Image Src,Gift Card
Vendor,,,,,,,,,,,,,,,,,
119 FASHION,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
7Heaven,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
ATTRAIT,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
AYANAPA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
AZAKA,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
BACI,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
BYE-BRA,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35
CANDY BRUSH,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
CIMINY,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
CRSM,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
D.N.D. RAW,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DISPLAY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DIVA LONDON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DROLE DE COPINE,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
EMAMODA,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
EVA&LOLA,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193
Envy,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
FIONELLA,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
FREESIA,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
G-LADIES,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
GOLDEN DAYS,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Kelyna,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Lily McBee,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
NIKKA,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
OBSESSIVE,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95
P.L,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
PINK BOOM,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
REDIAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
REDOX,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
SHAKO,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SINLY SHOES,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SOKY&SOKA,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71
SUNRISE C,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
YNS,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51

In [45]:
#By asking for the correct column, we can get a more clear answer
df.groupby('Vendor').count()["Type"]

Vendor
119 FASHION          4
7Heaven             40
ATTRAIT              4
AYANAPA              1
AZAKA               22
BACI               100
BYE-BRA             35
CANDY BRUSH          1
CIMINY              25
CRSM                36
D.N.D. RAW           1
DISPLAY              1
DIVA LONDON          1
DROLE DE COPINE      4
EMAMODA             51
EVA&LOLA           193
Envy                17
FIONELLA             2
FREESIA              9
G-LADIES             1
GOLDEN DAYS          2
Kelyna               1
Lily McBee           2
NIKKA                5
OBSESSIVE           95
P.L                  9
PINK BOOM           20
REDIAL               5
REDOX               24
SHAKO                1
SINLY SHOES          1
SOKY&SOKA           71
SUNRISE C            1
YNS                 51
Name: Type, dtype: int64